version: '3'
services:
  web:
    image: "sebby-simple-app"
    build: .
    command: "node server.js"
    ports:
      - "5001:5000"
  #   depends_on:
  #     - "mongo"
  # mongo:
  #   image: "mongo"
  #   ports:
  #     - "27017:27017"
